package org.example;

import java.rmi.RemoteException;
import java.rmi.server.UnicastRemoteObject;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.*;
import java.util.concurrent.TimeUnit;

public class PrintServices extends UnicastRemoteObject implements IPrintServices {
    HashMap<String,Long> sessionHashMap = new HashMap<String,Long>();
    public PrintServices() throws RemoteException{
        super();
    }

    private boolean sessionCheck(String sessionId){
        if (sessionHashMap.containsKey(sessionId)){
            long timeNano = System.nanoTime() - sessionHashMap.get(sessionId);
            long timeSec = TimeUnit.SECONDS.convert( timeNano,TimeUnit.NANOSECONDS);
            System.out.println("Time Elapsed= " + timeSec +" seconds");
            if (timeSec <= 10) {
                System.out.println("SessionId generated by the server for this session = " + sessionId);
                sessionHashMap.put(sessionId,System.nanoTime());
                return true;
            }
            else {
                sessionHashMap.remove(sessionId);
            }
        }
        return false;
    }
    @Override
    public Dictionary<String,Integer> signIn(String userId, String password) throws RemoteException {
        Dictionary<String,Integer> userInfo = new Hashtable<>();
        String session = null;
        int ulevel = 0;
        String url = "jdbc:mysql://localhost:3306/jdbcPrinterDB", username ="root", dbPassword="";
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection connection = DriverManager.getConnection(url,username,dbPassword);
            Statement statement = connection.createStatement();
            ResultSet resultSet = statement.executeQuery("select * from userprofile");
            while (resultSet.next()){
                if (resultSet.getString("userid").equals(userId) && resultSet.getString("password").equals(password)) {
                    Random random = new Random();
                    int sessionId = random.nextInt();
                    session =Integer.toString(sessionId);
                    sessionHashMap.put(session,System.nanoTime());
                    ulevel = resultSet.getInt("ulevel");
                    userInfo.put(session,ulevel);
                    System.out.println(session + " & " + ulevel);
                }
            }
            connection.close();
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
        return userInfo;
    }

    @Override
    public String echo(String input) throws RemoteException {
        return "From Server: "+ input;
    }

    @Override
    public String print(String filename, String printer, Dictionary<String,Integer> userInfo) throws RemoteException {
        String sessionId = userInfo.keys().nextElement();
        int uLevel = userInfo.get(sessionId);
        if (sessionCheck(sessionId)) {
            if (uLevel == UserLevelClass.manager || uLevel == UserLevelClass.powerUser || uLevel == UserLevelClass.ordinaryUser)
                return "Print the file= " + filename + " on printer = " + printer;
            else
                return "Access Denied!!!";
        }
        else
            return null;
    }

    @Override
    public String queue(String printer, Dictionary<String,Integer> userInfo) throws RemoteException {
        String sessionId = userInfo.keys().nextElement();
        int uLevel = userInfo.get(sessionId);
        if (sessionCheck(sessionId)) {
            if (uLevel == UserLevelClass.manager || uLevel == UserLevelClass.powerUser || uLevel == UserLevelClass.ordinaryUser)
                return "Print the queue of the printer = " + printer ;
            else
                return "Access Denied!!!";
        }
        else
            return null;
    }

    @Override
    public String topQueue(String printer, int job, Dictionary<String,Integer> userInfo) throws RemoteException {
        String sessionId = userInfo.keys().nextElement();
        int uLevel = userInfo.get(sessionId);
        if (sessionCheck(sessionId)) {
            if (uLevel == UserLevelClass.manager || uLevel == UserLevelClass.powerUser)
                return "Move the Job no = "+ job+ "of printer no= "+printer ;
            else
                return "Access Denied!!!";
        }
        else
            return null;
    }

    @Override
    public String start(Dictionary<String,Integer> userInfo) throws RemoteException {
        String sessionId = userInfo.keys().nextElement();
        int uLevel = userInfo.get(sessionId);
        if (sessionCheck(sessionId)) {
            if (uLevel == UserLevelClass.manager || uLevel == UserLevelClass.serviceTechnician)
                return "Start the printer." ;
            else
                return "Access Denied!!!";
        }
        else
            return null;
    }

    @Override
    public String stop(Dictionary<String,Integer> userInfo) throws RemoteException {
        String sessionId = userInfo.keys().nextElement();
        int uLevel = userInfo.get(sessionId);
        if (sessionCheck(sessionId)) {
            if (uLevel == UserLevelClass.manager || uLevel == UserLevelClass.serviceTechnician)
                return "Stop the printer" ;
            else
                return "Access Denied!!!";
        }
        else
            return null;
    }

    @Override
    public String restart(Dictionary<String,Integer> userInfo) throws RemoteException {
        String sessionId = userInfo.keys().nextElement();
        int uLevel = userInfo.get(sessionId);
        if (sessionCheck(sessionId)) {
            if (uLevel == UserLevelClass.manager || uLevel == UserLevelClass.powerUser || uLevel == UserLevelClass.serviceTechnician)
                return "Restart the Printer" ;
            else
                return "Access Denied!!!";
        }
        else
            return null;
    }

    @Override
    public String status(String printer, Dictionary<String,Integer> userInfo) throws RemoteException {
        String sessionId = userInfo.keys().nextElement();
        int uLevel = userInfo.get(sessionId);
        if (sessionCheck(sessionId)) {
            if (uLevel == UserLevelClass.manager || uLevel == UserLevelClass.serviceTechnician)
                return "The status of the printer no= " + printer ;
            else
                return "Access Denied!!!";
        }
        else
            return null;
    }

    @Override
    public String readConfig(String parameter, Dictionary<String,Integer> userInfo) throws RemoteException {
        String sessionId = userInfo.keys().nextElement();
        int uLevel = userInfo.get(sessionId);
        if (sessionCheck(sessionId)) {
            if (uLevel == UserLevelClass.manager || uLevel == UserLevelClass.serviceTechnician)
                return "The parameter is =" + parameter ;
            else
                return "Access Denied!!!";
        }
        else
            return null;
    }

    @Override
    public String setConfig(String parameter, String value, Dictionary<String,Integer> userInfo) throws RemoteException {
        String sessionId = userInfo.keys().nextElement();
        int uLevel = userInfo.get(sessionId);
        if (sessionCheck(sessionId)) {
            if (uLevel == UserLevelClass.manager || uLevel == UserLevelClass.serviceTechnician)
                return "Set the parameter = " + parameter+" with the value  = " + value ;
            else
                return "Access Denied!!!";
        }
        else
            return null;
    }
}
